// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZdOSRCc_F_B3lItEEItyN0UFK_xNuaY',
    appId: '1:538528191871:web:3b4c3eaec45fa52ce7764a',
    messagingSenderId: '538528191871',
    projectId: 'chat-app-4b187',
    authDomain: 'chat-app-4b187.firebaseapp.com',
    storageBucket: 'chat-app-4b187.appspot.com',
    measurementId: 'G-H81Q7JNEFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2AQG-j_ZK4i6fzhUH0-seFHBUzQ7W8uQ',
    appId: '1:538528191871:android:2af91663924ea5b8e7764a',
    messagingSenderId: '538528191871',
    projectId: 'chat-app-4b187',
    storageBucket: 'chat-app-4b187.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQk22k7UzD3I91ZeY9TLzMsaZyCuagsxQ',
    appId: '1:538528191871:ios:c0d0faab79645c65e7764a',
    messagingSenderId: '538528191871',
    projectId: 'chat-app-4b187',
    storageBucket: 'chat-app-4b187.appspot.com',
    iosClientId: '538528191871-n6u6srk2kn40tjvhhi33nkt8u26rnb25.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQk22k7UzD3I91ZeY9TLzMsaZyCuagsxQ',
    appId: '1:538528191871:ios:a828ab52047f8db1e7764a',
    messagingSenderId: '538528191871',
    projectId: 'chat-app-4b187',
    storageBucket: 'chat-app-4b187.appspot.com',
    iosClientId: '538528191871-v7f6gm5l0j1vioncp3befcethq2a5emt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
